spring:
  application:
    name: dqapi
  data:
    mongodb:
      uri: mongodb://localhost:27017

server:
  port: 8099
  forward-headers-strategy: native
  tomcat:
    relaxed-query-chars: "|,{,},[,]"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /admin/swagger
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info

dqualizer:
  leasingninja:
    webapp:
      process-path: "path-not-set"
    riskapi:
      process-path: "path-not-set"
  werkstatt:
    process-path: "path-not-set"
