spring:
  application:
    name: dqapi
  data:
    mongodb:
      host: dqdatabase
      auto-index-creation: true

server:
  port: 8099
  forward-headers-strategy: native
  tomcat:
    relaxed-query-chars: "|,{,},[,]"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /admin/swagger
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
